### ISSUE TITLE
Article does not demonstrate a way to record the Message ID

### ISSUE THREAD

**Issue by elbelcho** [MicrosoftDocs/powerapps-docs#2642]
Hello,
The "Enable users to discuss ideas" article does not demonstrate how to persist the Message ID to the Dataverse after capturing the ID to a local variable.  It appears that this information belongs under the "Update the submit button to capture the message ID" subheading as it demonstrates how to capture the ID to a local variable - but then that information is never written to the database.

Every other part of the equation is spelled out, but it is missing this critical piece. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ad672d-aff1-cde7-079f-54b81b00e013
* Version Independent ID: a6965ad7-43ad-6c6b-916b-6481640660d8
* Content: [Enable users to discuss ideas - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/extend-ideas-discussions#feedback)
* Content Source: [powerapps-docs/teams/extend-ideas-discussions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/extend-ideas-discussions.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @joel-lindstrom
* Microsoft Alias: **namarwah**

**Comment by ledgerg** [comment]
I am having this issue too - please share a response on how to post in the message ID to make this feature work :-)

**Comment by joel-lindstrom** [comment]
@tapanm-MSFT  this is fixed in this PR: https://github.com/MicrosoftDocs/powerapps-docs-pr/pull/5128
The issue is one of the formulas was cut off, omitting the patch

**Comment by ledgerg** [comment]
Hi

The link below is taking me to a 404 - Page not found, can you check the link and confirm this is correct? (I have logged into GitHub and still no difference)

Thanks

Graham
